- name: enable Elastic repo
  command: helm repo add elastic https://helm.elastic.co

- name: put values
  template: src=values.yml dest=/tmp/kibana-{{ kibana_helm_release }}.yml

- name: upgrade {{ kibana_helm_release }} release using a Helm chart
  command: helm upgrade {{ kibana_helm_release }} elastic/kibana --install --namespace {{ k8s_namespace }} -f /tmp/kibana-{{ kibana_helm_release }}.yml
